matrix:
  include:
  - language: node_js
    node_js:
     - "node"
    cache:
      directories:
        - "node_modules"
    notifications:
      email: false

  - language: python
    python:
        - "3.6"
    install:
        - pip install -r requirements.txt
    script:
        - pytest -v --pep8 -W ignore::UserWarning
    notifications:
        email: false